spring:
  mail:
    host: smtp.163.com
    username: yanagi_kon@163.com
    password: FJPYZZHINJPLOMDK
  datasource:
    url: jdbc:mysql://localhost:3306/book_manage
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    #开启SQL语句执行日志信息
    show-sql: true
    hibernate:
      #配置为自动创建
      ddl-auto: update
